buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 24  // 👈 MediaPipe는 최소 24 필요
        compileSdkVersion = 33
        targetSdkVersion = 33
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
    }
}